tinymce.addI18n('en', {
  'vyAI - Generate Content': 'vyAI - Generate Content',
  'Provide your input here': 'Provide your input here',
  'Enter your prompt or instruction...': 'Enter your prompt or instruction...',
  'Selected text will be used as context': 'Selected text will be used as context',
  Cancel: 'Cancel',
  Generate: 'Generate',
  'Please enter a prompt.': 'Please enter a prompt.',
  'vyAI configuration is missing. Please check your setup.': 'vyAI configuration is missing. Please check your setup.',
  'Generating...': 'Generating...',
  'Error generating content: ': 'Error generating content: ',
  'vyAI - Generated Content': 'vyAI - Generated Content',
  'Original Input:': 'Original Input:',
  'No text selected': 'No text selected',
  'Prompt:': 'Prompt:',
  'Generated Result:': 'Generated Result:',
  Retry: 'Retry',
  'Apply Changes': 'Apply Changes',
  'vyAI - Regenerating Content': 'vyAI - Regenerating Content',
  'Regenerating content with the same prompt...': 'Regenerating content with the same prompt...',
  'Error regenerating content: ': 'Error regenerating content: ',
  vyAI: 'vyAI',
  'Edit with vyAI': 'Edit with vyAI',
});
