tinymce.addI18n('fr', {
  'vyAI - Generate Content': 'vyAI - Générer du contenu',
  'Provide your input here': 'Fournissez votre saisie ici',
  'Enter your prompt or instruction...': 'Entrez votre prompt ou instruction...',
  'Selected text will be used as context': 'Le texte sélectionné sera utilisé comme contexte',
  Cancel: 'Annuler',
  Generate: 'Générer',
  'Please enter a prompt.': 'Veuillez entrer un prompt.',
  'vyAI configuration is missing. Please check your setup.': 'La configuration vyAI est manquante. Veuillez vérifier votre configuration.',
  'Generating...': 'Génération...',
  'Error generating content: ': 'Erreur lors de la génération du contenu : ',
  'vyAI - Generated Content': 'vyAI - Contenu généré',
  'Original Input:': 'Saisie originale :',
  'No text selected': 'Aucun texte sélectionné',
  'Prompt:': 'Prompt :',
  'Generated Result:': 'Résultat généré :',
  Retry: 'Réessayer',
  'Apply Changes': 'Appliquer les modifications',
  'vyAI - Regenerating Content': 'vyAI - Régénération du contenu',
  'Regenerating content with the same prompt...': 'Régénération du contenu avec le même prompt...',
  'Error regenerating content: ': 'Erreur lors de la régénération du contenu : ',
  vyAI: 'vyAI',
  'Edit with vyAI': 'Modifier avec vyAI',
});
